HAI Fix Spring Boot 3.2.0 update
Remove HasId<ID> interface implementation from entities. I don't know
why, but this cause exceptions when loading the related repositories. I
suspect it's related to HasId having a type parameter, but I'm not sure.
The exception was:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hankeRepository' defined in fi.hel.haitaton.hanke.HankeRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration
    Caused by:
    org.springframework.data.mapping.MappingException: Failed to obtain BeanInfo for class [fi.hel.haitaton.hanke.HankeEntity]
        Caused by:
        org.springframework.beans.FatalBeanException: Failed to obtain BeanInfo for class [fi.hel.haitaton.hanke.HankeEntity]
            Caused by:
            java.beans.IntrospectionException: type mismatch between read and write methods
```

Inline `mergeDataInto` to it's only call site. Since entities can't have
the HasId interface, `mergeDataInto` would need changes that would make
it less reusable. Remove the tests for it.

Configure tests to use random ports again. After the update, tests
started to fail with `Port 8081 is already in use` errors. Earlier, the
tests were set to run in random ports by setting `webEnvironment =
WebEnvironment.RANDOM_PORT` in `@SpringBootTest`. Setting the port to be
random in the properties means that it only needs to be configured once.

Add an exception handler for NoResourceFoundException. After the update,
TestDataController endpoints started to return 500 Internal error when
they were called with the controller disabled by environment variables.
Before the update, they returned 404 Not Found. The added exception
handler returns the expected behaviour.