HAI-1345 Fix for database migrations (#274)
The previous commit for HAI-1345 deleted all applications because the
existing applications are not linked with hankkeet. Unfortunately, they
remove deleted only after the migration adding the foreign key from
applications to hanke. So if there are applications, the migration will
fail with
```
org.postgresql.util.PSQLException: ERROR: column "hanke_id" of relation "applications" contains null values
```

To fix this, do the delete before adding the foreign key.

Modifying migrations afterwards is kind of taboo, but it should be fine
in this instance, since the migrations haven't been deployed anywhere
yet.